SELECT D.CONTRACT, D.SUMM FROM
(select 
fc.ID_CONTRACT_INST CONTRACT, 
sum(fsc.N_COST_PERIOD) SUMM
from fw_contracts fc
join FW_SERVICES_COST fsc
on fsc.ID_CONTRACT_INST  = fc.ID_CONTRACT_INST
AND fsc.DT_START <= CURRENT_TIMESTAMP
AND fsc.DT_STOP > CURRENT_TIMESTAMP
where fc.DT_START <= CURRENT_TIMESTAMP
AND fc.DT_STOP > CURRENT_TIMESTAMP
group by fc.id_contract_inst) D
JOIN
(select 
fc.ID_CONTRACT_INST CONTR, 
avg(fsc.N_COST_PERIOD) avgg
from fw_contracts fc
join FW_SERVICES_COST fsc
on fsc.ID_CONTRACT_INST  = fc.ID_CONTRACT_INST
AND fsc.DT_START <= CURRENT_TIMESTAMP
AND fsc.DT_STOP > CURRENT_TIMESTAMP
where fc.DT_START <= CURRENT_TIMESTAMP
AND fc.DT_STOP > CURRENT_TIMESTAMP
group by fc.id_contract_inst)
ON CONTR = CONTRACT
AND SUMM > avgg;